name: ticketplus
description: "A new Flutter project."
# A linha seguinte impede que o pacote seja publicado acidentalmente no pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS (já vinha no projeto original)
  cupertino_icons: ^1.0.2

  # --- Novas dependências adicionadas ---
  # Para renderizar o mapa com marcadores
  google_maps_flutter: ^2.5.0

  # Para persistência de dados local (banco de dados SQLite)
  sqflite: ^2.3.0

  # Auxiliar para encontrar o diretório correto de arquivos no Android/iOS
  path: ^1.8.3

  # Para obter a localização atual do dispositivo (GPS)
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Regras de boas práticas (Lints)
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true